steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/ninja-tutor-backend", "."]

  # Push the Docker image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/ninja-tutor-backend"]

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "ninja-tutor-backend"
      - "--image"
      - "gcr.io/$PROJECT_ID/ninja-tutor-backend"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--max-instances"
      - "10"
      - "--timeout"
      - "300"
      - "--concurrency"
      - "80"

images:
  - "gcr.io/$PROJECT_ID/ninja-tutor-backend"
